### ISSUE TITLE
1.19 and bedrock support

### ISSUE THREAD

**Issue by ItsRedly** [psu-de/MineSharp#16]
Hi.
So im actually making my own minecraft client based on MineSharp and i would love to ask.
Can you guys please implement 1.19 and bedrock suport? Bedrock is easy cause ConcreteMC/Alex already has it.
But about 1.19. Why did no one implement it yet? Is it because of missing docs or what?
Also I would love to collab to add some more features.

Please continue this conversation using e-mail or discord:
    - Email: alvesdinis74@gmail.com
    - Discord: ItsRedly#1174

Thank you.

**Comment by psu-de** [comment]
Hey, 
currently my goal is to fully support Java 1.18.1. From there I plan to support multiple versions.
I have currenlty not the time to work on many big tasks. however I welcome any contributions to this.
