### ISSUE TITLE
Move command doesn't work

### ISSUE THREAD

**Issue by pyth0nic** [psu-de/MineSharp#3]
Hello,

Really like the project and the command line interface with autocomplete is very cool. Just having an issue with `move Forward` for example.
```
An error occurred while performing command!
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at bool System.Collections.Generic.List`1.Enumerator.MoveNext()
  at void MineSharp.ConsoleClient.Console.Commands.Misc.BotLogCommand.DoAction(string[] argv, CancellationToken
```

**Comment by psu-de** [comment]
Hey,

the physics module is currently still very buggy and needs a rework. Currently I'm refactoring the MineSharp.Data Project.

**Comment by pyth0nic** [comment]
Hi hi,

Fair enough, yeah I can have a crack. Could be good to create a slack channel or gitter to share the knowledge. Any thoughts?

**Comment by psu-de** [comment]
Good idea! I've created a gitter room: 
https://gitter.im/MineSharp-net/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link
I don't know very much about Minecraft Physics, but I'll try to help out.

**Comment by psu-de** [comment]
Move command should work again (except jump) after the last commit  :-)
