### ISSUE TITLE
GameMode enum may be incorrect

### ISSUE THREAD

**Issue by jasongdove** [psu-de/MineSharp#39]
Is the game mode enum correct? I have a simple bot that automatically switches to spectator mode at night time, something like:

```csharp
    if (currentTime is >= 12_542 and <= 23_459)
    {
        if (player.GameMode is not GameMode.Spectator)
        {
            await chat.SendCommand("gamemode spectator");
        }
    }
```

This correctly sets the game mode, but the issue is that it runs the command every time through the loop, because `player.GameMode` reports as `GameMode.Adventure` not `GameMode.Spectator`.

Are these final two values correct, or should they be 2 and 3?

https://github.com/psu-de/MineSharp/blob/091d617b7f59aec1d98aa0aaddc35e0c714a1701/MineSharp.Core/Common/GameMode.cs#L18-L26

`Update Game Mode` doesn't have any notes here: https://wiki.vg/Protocol#Player_Info_Update but other sections have it defined, like here https://wiki.vg/Protocol#Game_Event

```
3 	Change game mode 	0: Survival, 1: Creative, 2: Adventure, 3: Spectator. 
```

**Comment by psu-de** [comment]
Yes, you're right. Thanks for pointing this out!
