### ISSUE TITLE
Creative items

### ISSUE THREAD

**Issue by CorruptionHades** [psu-de/MineSharp#42]
How can I make the bot get an item from the creative inventory?
I tried these:

```c# 
ItemInfo diamond = bot.Data.Items.ByName("diamond")!;
bot.GetPlugin<WindowPlugin>().Inventory!.SetSlot(new Slot(new Item(diamond, 1, null, null), 1));
```

and also this

```c#
ItemInfo diamond = bot.Data.Items.ByName("diamond")!;
        
Window mainInventory = new Window(255, "", 4 * 9, null, null);
Window inventory     = new Window(0, "Inventory", 9, mainInventory, null);

inventory.SetSlot(new Slot(new Item(diamond, 1, null, null), 1));
        
 ```

but both don't work

also how does mining work?

when I do

```c#
Block b = worldPl.World.GetBlockAt(new Position(x, y, z));

await worldPl.MineBlock(b, BlockFace.Top);
```
nothing happens

**Comment by CorruptionHades** [comment]
So the mining works when I try it with a vanilla server but on spigot it doesn't work

**Comment by psu-de** [comment]
Hey,
it is not documented anywhere, but generally you should never use `window.SetSlot()` with windows from `WindowPlugin`.
If you use `SetSlot`, the client and the server window will get out of sync.

I haven't implemented any creative inventory logic yet, but i'll add it to the todo list.

**Comment by CorruptionHades** [comment]
nice ty

**Comment by CorruptionHades** [comment]
alright I made the packet for creative inventory item getting and got it working.
![image](https://github.com/psu-de/MineSharp/assets/96599430/b137f46c-21c9-49cb-9932-8117fcba49f5)
Also added it to the registry
![image](https://github.com/psu-de/MineSharp/assets/96599430/d5f486d4-1ace-47f0-ac0c-0b6b4d39f6e2)

(I didn't clone the repo correctly so I can't make a pull request sorry)

**Comment by psu-de** [comment]
oh thanks a lot, i will add it myself if thats okay for you

**Comment by CorruptionHades** [comment]
ye sure

**Comment by psu-de** [comment]
Okay, so I have added the packet and `CreativeInventory` in `WindowPlugin`.

The creative inventory is accessible with `bot.GetPlugin<WindowPlugin>().CreativeInventory`.
The creative inventory supports 
 - `CreativeInventory.Available`, indicating whether the creative inventory is available and
 - `CreativeInventory.GetItem(ItemType type, byte count, short inventorySlotIndex)` which places _count_ items of type _type_ in the bots inventory at index _inventorySlotIndex_.
