### ISSUE TITLE
sometimes when the bot is disconnected from the server, it doesn't invoke the MineSharpBot.OnBotDisconnected 

### ISSUE THREAD

**Issue by qwqtoday** [psu-de/MineSharp#46]
it's actually not sometimes, it's most of the time. it happens a lot so I can't even detect when the bot is disconnected.

**Comment by TheVeryStarlk** [comment]
It seems to be working fine with me. Can you share us the steps for repo?

**Comment by qwqtoday** [comment]
> It seems to be working fine with me. Can you share us the steps for repo?

Sorry I forgot to close this issue, I fixed this myself
