### ISSUE TITLE
Compile time version selection by using preprocessor directives

### ISSUE THREAD

**Issue by qwqtoday** [psu-de/MineSharp#57]
Currently minesharp compiles every version data to MimeSharp.Data, which makes the compiled output bigger than it's needs. If we use preprocessor directives to declare version at compile time, the compiler won't include all version data to compiled output, which makes the output smaller.

We can also take advantage of this to create version specific features so we can have the unnecessary features of a specific version not to compile. This makes the code will potentially run faster because the if checks at runtime is already gone on versions thst if check is unnecessary on.

**Comment by psu-de** [comment]
I thought about that, but there are some problems with that.
You'd need to compile MineSharp.Data for every minecraft version everytime you make a change.
Supporting multiple minecraft versions would also be harder with different assemblies for each version...

And MineSharp uses data parsed from json files now anyways.
